version: "3"
services:
  db:
    image: mariadb
    container_name: db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: TODO_DB
      MYSQL_USER: usr
      MYSQL_PASSWORD: TjpLxscak6rq
      MYSQL_ROOT_PASSWORD: JkAUaMNRmaD8
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_VERBOSE: TODO_DB
      PMA_PORT: 3306
    depends_on:
      - db
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db-data:
    driver: local
