version: "3"

services:
  php:
    container_name: php
    image: php:7.4-apache
    build:
      context: ./docker/php
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
    ports:
      - 8080:80
  db:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=JkAUaMNRmaD8
      - MYSQL_DATABASE=todo_list
      - MYSQL_USER=usr
      - MYSQL_PASSWORD=TjpLxscak6rq
      - TZ=Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  phpmyadmin:
    container_name: pmadm
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=usr
      - PMA_PASSWORD=TjpLxscak6rq
    links:
      - db
    ports:
      - 4040:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
