version: "3"

services:
  php:
    image: php:7.4-apache
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
    ports:
      - 8080:80
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=JkAUaMNRmaD8
      - MYSQL_DATABASE=todo_list
      - MYSQL_USER=usr
      - MYSQL_PASSWORD=TjpLxscak6rq
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=usr
      - PMA_PASSWORD=TjpLxscak6rq
    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
